import { Property, Guest, Booking } from "./types";

export const mockProperties: Property[] = [
  {
    id: "kemaman-1",
    name: "Kemaman 1",
    address: "Chukai, Kemaman, Terengganu",
    base_price_per_night: 250,
    price_direct: 250,       // Direct WhatsApp tanpa komisen
    price_airbnb: 295,       // Airbnb (caj platform)
    price_bookingcom: 305,   // Booking.com (caj OTA)
    cleaning_fee: 50,
    deposit_amount: 100,
    total_rooms: 3,
    max_guests: 8,
    smartlock_code: "8899#",
    wifi_ssid: "DamaiKemaman1_5G",
    wifi_password: "damai2026!",
    status: "active",
  },
  {
    id: "kemaman-2",
    name: "Kemaman 2",
    address: "Chukai, Kemaman, Terengganu",
    base_price_per_night: 220,
    price_direct: 220,
    price_airbnb: 260,
    price_bookingcom: 270,
    cleaning_fee: 40,
    deposit_amount: 100,
    total_rooms: 2,
    max_guests: 6,
    smartlock_code: "4422#",
    wifi_ssid: "DamaiKemaman2_WiFi",
    wifi_password: "damai2026!",
    status: "active",
  },
  {
    id: "gong-badak",
    name: "Gong Badak",
    address: "Gong Badak, Kuala Terengganu, Terengganu",
    base_price_per_night: 300,
    price_direct: 300,
    price_airbnb: 350,
    price_bookingcom: 365,
    cleaning_fee: 60,
    deposit_amount: 150,
    total_rooms: 4,
    max_guests: 10,
    smartlock_code: "1234#",
    wifi_ssid: "DamaiGongBadak_Guest",
    wifi_password: "damai2026!",
    status: "active",
  },
];

export const mockGuests: Guest[] = [
  {
    id: "gst-1",
    name: "En. Azman",
    phone: "0123456789",
    email: "azman@example.com",
    notes: "Booking via Direct WhatsApp",
  },
  {
    id: "gst-2",
    name: "Nurul Huda",
    phone: "0198765432",
    email: "huda@example.com",
    notes: "Repeat guest - Kemaman 2",
  },
  {
    id: "gst-3",
    name: "Tan Wei Lun",
    phone: "0123344556",
    email: "weilun@example.com",
    notes: "Gong Badak family trip",
  },
];

export const mockBookings: Booking[] = [
  {
    id: "bk-101",
    property_id: "kemaman-1",
    guest_id: "gst-1",
    check_in: "2026-09-20",
    check_out: "2026-09-22",
    total_nights: 2,
    total_price: 550,
    deposit_amount: 100,
    source: "direct_whatsapp",
    booking_status: "confirmed",
    payment_status: "deposit_paid",
    notes: "En. Azman - 0123456789 (Data Booking Planner)",
    property: mockProperties[0],
    guest: mockGuests[0],
  },
  {
    id: "bk-102",
    property_id: "kemaman-2",
    guest_id: "gst-2",
    check_in: "2026-09-19",
    check_out: "2026-09-21",
    total_nights: 2,
    total_price: 480,
    deposit_amount: 100,
    source: "airbnb",
    booking_status: "checked_in",
    payment_status: "fully_paid",
    notes: "Airbnb Kemaman 2",
    property: mockProperties[1],
    guest: mockGuests[1],
  },
  {
    id: "bk-103",
    property_id: "gong-badak",
    guest_id: "gst-3",
    check_in: "2026-09-25",
    check_out: "2026-09-27",
    total_nights: 2,
    total_price: 660,
    deposit_amount: 150,
    source: "booking_com",
    booking_status: "confirmed",
    payment_status: "deposit_paid",
    notes: "Booking.com Gong Badak",
    property: mockProperties[2],
    guest: mockGuests[2],
  },
];