import { Property, Guest, Booking } from "./types";

export const mockProperties: Property[] = [
  {
    id: "kemaman-1",
    name: "Homestay Kenangan Kemaman 1",
    address: "Chukai, Kemaman, Terengganu (Rumah Belakang)",
    rental_type: "monthly",
    monthly_rental_rate: 700,
    base_price_per_night: 0,
    price_direct: 0,
    price_airbnb: 0,
    price_bookingcom: 0,
    cleaning_fee: 0,
    deposit_amount: 700,
    total_rooms: 2,
    total_bathrooms: 1,
    total_toilets: 1,
    max_guests: 4,
    smartlock_code: "8899#",
    wifi_ssid: "HomestayKenangan_Kemaman",
    wifi_password: "kenangan2026!",
    google_maps_url: "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
    notes: "Kini dijadikan sewaan bilik bulanan (Room Rental) - RM 700 / bulan. Rumah belakang.",
    status: "active",
  },
  {
    id: "kemaman-2",
    name: "Homestay Kenangan Kemaman 2",
    address: "Chukai, Kemaman, Terengganu (Rumah Depan)",
    rental_type: "daily",
    base_price_per_night: 180,
    price_direct: 180,       // Direct WhatsApp
    price_airbnb: 215,       // Airbnb (caj platform)
    price_bookingcom: 225,   // Booking.com (caj OTA)
    cleaning_fee: 40,
    deposit_amount: 100,
    total_rooms: 3,
    total_bathrooms: 1,
    total_toilets: 1,
    max_guests: 8,
    smartlock_code: "4422#",
    wifi_ssid: "HomestayKenangan_Kemaman",
    wifi_password: "kenangan2026!",
    google_maps_url: "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
    notes: "Rumah depan (3 bilik, 1 toilet, 1 bathroom). Lokasi & kemudahan sama dengan Kemaman 1.",
    status: "active",
  },
  {
    id: "gong-badak",
    name: "Homestay Kenangan Gong Badak",
    address: "Gong Badak, Kuala Terengganu, Terengganu",
    rental_type: "daily",
    base_price_per_night: 350,
    price_direct: 350,       // Direct WhatsApp
    price_airbnb: 395,       // Airbnb
    price_bookingcom: 410,   // Booking.com
    cleaning_fee: 60,
    deposit_amount: 150,
    total_rooms: 4,
    total_bathrooms: 4,
    total_toilets: 4,
    max_guests: 12,
    smartlock_code: "1234#",
    wifi_ssid: "HomestayKenangan_KT",
    wifi_password: "kenangan2026!",
    google_maps_url: "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
    notes: "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
    status: "active",
  },
];

export const mockGuests: Guest[] = [
  {
    "id": "gst-1",
    "name": "Family Gathering AimaSukri",
    "phone": "0190000001",
    "email": "familygatheringaimasukri@gmail.com",
    "notes": "Booking Planner: Family Gathering AimaSukri 22/5 - 29/5 (cuti sekolah) (1 malam)",
    "created_at": "2026-09-24T11:46:42.217Z"
  },
  {
    "id": "gst-2",
    "name": "Abg",
    "phone": "0190000002",
    "email": "abg@gmail.com",
    "notes": "Booking Planner: Abg (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-3",
    "name": "Penyelenggaraan Kemaman 1",
    "phone": "0190000000",
    "email": "penyelenggaraankemaman1@gmail.com",
    "notes": "Tarikh Disekat / Penyelenggaraan (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-4",
    "name": "Aqiqah",
    "phone": "0190000003",
    "email": "aqiqah@gmail.com",
    "notes": "Booking Planner: Aqiqah (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-5",
    "name": "Pelanggan Airbnb Rebooked",
    "phone": "0190000004",
    "email": "pelangganairbnbrebooked@gmail.com",
    "notes": "Booking Planner: Airbnb rebooked (2 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-6",
    "name": "Penyelenggaraan GB",
    "phone": "0190000000",
    "email": "penyelenggaraangb@gmail.com",
    "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-7",
    "name": "Romestay 3",
    "phone": "0190000005",
    "email": "romestay3@gmail.com",
    "notes": "Booking Planner: Romestay 3 (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-8",
    "name": "Romstay",
    "phone": "0190000006",
    "email": "romstay@gmail.com",
    "notes": "Booking Planner: Romstay (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-9",
    "name": "Romestay",
    "phone": "0190000007",
    "email": "romestay@gmail.com",
    "notes": "Booking Planner: Romestay (2 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-10",
    "name": "Booking.com Guest",
    "phone": "0190000008",
    "email": "bookingcomguest@gmail.com",
    "notes": "Booking Planner: Booking.com (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-11",
    "name": "Sewa Setahun",
    "phone": "0190000009",
    "email": "sewasetahun@gmail.com",
    "notes": "Booking Planner: Sewa setahun (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-12",
    "name": "Arif Zulkifli",
    "phone": "0129881122",
    "email": "arifzulkifli@gmail.com",
    "notes": "Booking Planner: Arif zulkifli Sewa 1 Ogos 2026 (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-13",
    "name": "Direct Booking 1 Ogos",
    "phone": "0120000000",
    "email": "directbooking1ogos@gmail.com",
    "notes": "Booking Planner: Direct Booking 1 Ogos 2026 (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-14",
    "name": "Athirah",
    "phone": "0198887766",
    "email": "athirah@gmail.com",
    "notes": "Booking Planner: Stay 1 hari Athirah (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-15",
    "name": "Kamariah (Majlis Kahwin)",
    "phone": "0176655443",
    "email": "kamariahmajliskahwin@gmail.com",
    "notes": "Booking Planner: Boleh confirm tarikh check in dan check out Majlis Kahwin Nama: Kamariah (2 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-16",
    "name": "Pelanggan Airbnb Kemaman 2",
    "phone": "0167788990",
    "email": "pelangganairbnbkemaman2@gmail.com",
    "notes": "Booking Planner: Tarikh Disekat / Penyelenggaraan (3 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-17",
    "name": "Pelanggan Airbnb Gong Badak",
    "phone": "0167788991",
    "email": "pelangganairbnbgongbadak@gmail.com",
    "notes": "Booking Planner: Tarikh Disekat / Penyelenggaraan (7 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-18",
    "name": "En. Halim (Penyewa Sewa Bulanan)",
    "phone": "0134455667",
    "email": "enhalimpenyewasewabulanan@gmail.com",
    "notes": "Booking Planner: Sewa (1 malam) Sewaan Bilik Bulanan Tetap RM700/bulan",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-19",
    "name": "Standby",
    "phone": "0190000010",
    "email": "standby@gmail.com",
    "notes": "Booking Planner: Standby (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-20",
    "name": "Wiraday",
    "phone": "0193344552",
    "email": "wiraday@gmail.com",
    "notes": "Booking Planner: Wiraday (3 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-21",
    "name": "Penyelenggaraan K2",
    "phone": "0190000000",
    "email": "penyelenggaraank2@gmail.com",
    "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-22",
    "name": "Dh byr depo utk kawen",
    "phone": "0182233445",
    "email": "dhbyrdepoutkkawen@gmail.com",
    "notes": "Booking Planner: Dh byr depo utk kawen (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-23",
    "name": "Dh byr depo utk majlis kawen",
    "phone": "0182233446",
    "email": "dhbyrdepoutkmajliskawen@gmail.com",
    "notes": "Booking Planner: Dh byr depo utk majlis kawen (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-24",
    "name": "Konvo",
    "phone": "0197766554",
    "email": "konvo@gmail.com",
    "notes": "Booking Planner: Konvo (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-25",
    "name": "Muhammad Fikri bin Ismail",
    "phone": "01139618066",
    "email": "muhammadfikribinismail@gmail.com",
    "notes": "Booking Planner: Nama: Muhammad Fikri bin Ismail No. Telefon: 01139618066 (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  },
  {
    "id": "gst-26",
    "name": "Tarikh Disekat / Penyelenggaraan",
    "phone": "0190000000",
    "email": "tarikhdisekatpenyelenggaraan@gmail.com",
    "notes": "Tarikh Disekat / Penyelenggaraan (33 malam)",
    "created_at": "2026-09-24T11:46:42.234Z"
  }
];

export const mockBookings: Booking[] = [
  {
    "id": "bk-verified-1",
    "property_id": "gong-badak",
    "guest_id": "gst-1",
    "check_in": "2026-05-22",
    "check_out": "2026-05-23",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Booking Planner: Family Gathering AimaSukri 22/5 - 29/5 (cuti sekolah) (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-1",
      "name": "Family Gathering AimaSukri",
      "phone": "0190000001",
      "email": "familygatheringaimasukri@gmail.com",
      "notes": "Booking Planner: Family Gathering AimaSukri 22/5 - 29/5 (cuti sekolah) (1 malam)",
      "created_at": "2026-09-24T11:46:42.217Z"
    }
  },
  {
    "id": "bk-verified-2",
    "property_id": "kemaman-2",
    "guest_id": "gst-2",
    "check_in": "2026-05-22",
    "check_out": "2026-05-23",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Booking Planner: Abg (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-2",
      "name": "Homestay Kenangan Kemaman 2",
      "address": "Chukai, Kemaman, Terengganu (Rumah Depan)",
      "rental_type": "daily",
      "base_price_per_night": 180,
      "price_direct": 180,
      "price_airbnb": 215,
      "price_bookingcom": 225,
      "cleaning_fee": 40,
      "deposit_amount": 100,
      "total_rooms": 3,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 8,
      "smartlock_code": "4422#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Rumah depan (3 bilik, 1 toilet, 1 bathroom). Lokasi & kemudahan sama dengan Kemaman 1.",
      "status": "active"
    },
    "guest": {
      "id": "gst-2",
      "name": "Abg",
      "phone": "0190000002",
      "email": "abg@gmail.com",
      "notes": "Booking Planner: Abg (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-3",
    "property_id": "gong-badak",
    "guest_id": "gst-1",
    "check_in": "2026-05-23",
    "check_out": "2026-05-24",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Booking Planner: Family Gathering AimaSukri 22/5 - 29/5 (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-1",
      "name": "Family Gathering AimaSukri",
      "phone": "0190000001",
      "email": "familygatheringaimasukri@gmail.com",
      "notes": "Booking Planner: Family Gathering AimaSukri 22/5 - 29/5 (cuti sekolah) (1 malam)",
      "created_at": "2026-09-24T11:46:42.217Z"
    }
  },
  {
    "id": "bk-verified-4",
    "property_id": "gong-badak",
    "guest_id": "gst-1",
    "check_in": "2026-05-24",
    "check_out": "2026-05-28",
    "total_nights": 4,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Booking Planner: Family Gathering AimaSukri 22/5 - 29/5 (4 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-1",
      "name": "Family Gathering AimaSukri",
      "phone": "0190000001",
      "email": "familygatheringaimasukri@gmail.com",
      "notes": "Booking Planner: Family Gathering AimaSukri 22/5 - 29/5 (cuti sekolah) (1 malam)",
      "created_at": "2026-09-24T11:46:42.217Z"
    }
  },
  {
    "id": "bk-verified-5",
    "property_id": "kemaman-1",
    "guest_id": "gst-3",
    "check_in": "2026-05-27",
    "check_out": "2026-05-28",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Tarikh Disekat / Penyelenggaraan (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-1",
      "name": "Homestay Kenangan Kemaman 1",
      "address": "Chukai, Kemaman, Terengganu (Rumah Belakang)",
      "rental_type": "monthly",
      "monthly_rental_rate": 700,
      "base_price_per_night": 0,
      "price_direct": 0,
      "price_airbnb": 0,
      "price_bookingcom": 0,
      "cleaning_fee": 0,
      "deposit_amount": 700,
      "total_rooms": 2,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 4,
      "smartlock_code": "8899#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Kini dijadikan sewaan bilik bulanan (Room Rental) - RM 700 / bulan. Rumah belakang.",
      "status": "active"
    },
    "guest": {
      "id": "gst-3",
      "name": "Penyelenggaraan Kemaman 1",
      "phone": "0190000000",
      "email": "penyelenggaraankemaman1@gmail.com",
      "notes": "Tarikh Disekat / Penyelenggaraan (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-6",
    "property_id": "gong-badak",
    "guest_id": "gst-4",
    "check_in": "2026-05-28",
    "check_out": "2026-05-29",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Booking Planner: Aqiqah (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-4",
      "name": "Aqiqah",
      "phone": "0190000003",
      "email": "aqiqah@gmail.com",
      "notes": "Booking Planner: Aqiqah (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-7",
    "property_id": "gong-badak",
    "guest_id": "gst-1",
    "check_in": "2026-05-29",
    "check_out": "2026-05-30",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Booking Planner: Family Gathering AimaSukri 22/5 - 29/5 (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-1",
      "name": "Family Gathering AimaSukri",
      "phone": "0190000001",
      "email": "familygatheringaimasukri@gmail.com",
      "notes": "Booking Planner: Family Gathering AimaSukri 22/5 - 29/5 (cuti sekolah) (1 malam)",
      "created_at": "2026-09-24T11:46:42.217Z"
    }
  },
  {
    "id": "bk-verified-8",
    "property_id": "gong-badak",
    "guest_id": "gst-5",
    "check_in": "2026-05-30",
    "check_out": "2026-06-01",
    "total_nights": 2,
    "total_price": 766,
    "deposit_amount": 100,
    "source": "airbnb",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Airbnb rebooked (2 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-5",
      "name": "Pelanggan Airbnb Rebooked",
      "phone": "0190000004",
      "email": "pelangganairbnbrebooked@gmail.com",
      "notes": "Booking Planner: Airbnb rebooked (2 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-9",
    "property_id": "gong-badak",
    "guest_id": "gst-6",
    "check_in": "2026-06-03",
    "check_out": "2026-06-05",
    "total_nights": 2,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-6",
      "name": "Penyelenggaraan GB",
      "phone": "0190000000",
      "email": "penyelenggaraangb@gmail.com",
      "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-10",
    "property_id": "gong-badak",
    "guest_id": "gst-6",
    "check_in": "2026-06-07",
    "check_out": "2026-06-08",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Tarikh Disekat / Penyelenggaraan (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-6",
      "name": "Penyelenggaraan GB",
      "phone": "0190000000",
      "email": "penyelenggaraangb@gmail.com",
      "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-11",
    "property_id": "gong-badak",
    "guest_id": "gst-6",
    "check_in": "2026-06-14",
    "check_out": "2026-06-17",
    "total_nights": 3,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Tarikh Disekat / Penyelenggaraan (3 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-6",
      "name": "Penyelenggaraan GB",
      "phone": "0190000000",
      "email": "penyelenggaraangb@gmail.com",
      "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-12",
    "property_id": "gong-badak",
    "guest_id": "gst-7",
    "check_in": "2026-06-25",
    "check_out": "2026-06-26",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Booking Planner: Romestay 3 (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-7",
      "name": "Romestay 3",
      "phone": "0190000005",
      "email": "romestay3@gmail.com",
      "notes": "Booking Planner: Romestay 3 (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-13",
    "property_id": "gong-badak",
    "guest_id": "gst-6",
    "check_in": "2026-06-30",
    "check_out": "2026-07-01",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Tarikh Disekat / Penyelenggaraan (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-6",
      "name": "Penyelenggaraan GB",
      "phone": "0190000000",
      "email": "penyelenggaraangb@gmail.com",
      "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-14",
    "property_id": "gong-badak",
    "guest_id": "gst-8",
    "check_in": "2026-07-01",
    "check_out": "2026-07-02",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Booking Planner: Romstay (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-8",
      "name": "Romstay",
      "phone": "0190000006",
      "email": "romstay@gmail.com",
      "notes": "Booking Planner: Romstay (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-15",
    "property_id": "gong-badak",
    "guest_id": "gst-9",
    "check_in": "2026-07-02",
    "check_out": "2026-07-04",
    "total_nights": 2,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Booking Planner: Romestay (2 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-9",
      "name": "Romestay",
      "phone": "0190000007",
      "email": "romestay@gmail.com",
      "notes": "Booking Planner: Romestay (2 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-16",
    "property_id": "kemaman-1",
    "guest_id": "gst-10",
    "check_in": "2026-07-11",
    "check_out": "2026-07-12",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "booking_com",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Booking Planner: Booking.com (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-1",
      "name": "Homestay Kenangan Kemaman 1",
      "address": "Chukai, Kemaman, Terengganu (Rumah Belakang)",
      "rental_type": "monthly",
      "monthly_rental_rate": 700,
      "base_price_per_night": 0,
      "price_direct": 0,
      "price_airbnb": 0,
      "price_bookingcom": 0,
      "cleaning_fee": 0,
      "deposit_amount": 700,
      "total_rooms": 2,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 4,
      "smartlock_code": "8899#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Kini dijadikan sewaan bilik bulanan (Room Rental) - RM 700 / bulan. Rumah belakang.",
      "status": "active"
    },
    "guest": {
      "id": "gst-10",
      "name": "Booking.com Guest",
      "phone": "0190000008",
      "email": "bookingcomguest@gmail.com",
      "notes": "Booking Planner: Booking.com (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-17",
    "property_id": "kemaman-1",
    "guest_id": "gst-11",
    "check_in": "2026-07-24",
    "check_out": "2026-07-25",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Booking Planner: Sewa setahun (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-1",
      "name": "Homestay Kenangan Kemaman 1",
      "address": "Chukai, Kemaman, Terengganu (Rumah Belakang)",
      "rental_type": "monthly",
      "monthly_rental_rate": 700,
      "base_price_per_night": 0,
      "price_direct": 0,
      "price_airbnb": 0,
      "price_bookingcom": 0,
      "cleaning_fee": 0,
      "deposit_amount": 700,
      "total_rooms": 2,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 4,
      "smartlock_code": "8899#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Kini dijadikan sewaan bilik bulanan (Room Rental) - RM 700 / bulan. Rumah belakang.",
      "status": "active"
    },
    "guest": {
      "id": "gst-11",
      "name": "Sewa Setahun",
      "phone": "0190000009",
      "email": "sewasetahun@gmail.com",
      "notes": "Booking Planner: Sewa setahun (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-18",
    "property_id": "kemaman-1",
    "guest_id": "gst-12",
    "check_in": "2026-08-01",
    "check_out": "2026-08-02",
    "total_nights": 1,
    "total_price": 700,
    "deposit_amount": 100,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Arif zulkifli Sewa 1 Ogos 2026 (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-1",
      "name": "Homestay Kenangan Kemaman 1",
      "address": "Chukai, Kemaman, Terengganu (Rumah Belakang)",
      "rental_type": "monthly",
      "monthly_rental_rate": 700,
      "base_price_per_night": 0,
      "price_direct": 0,
      "price_airbnb": 0,
      "price_bookingcom": 0,
      "cleaning_fee": 0,
      "deposit_amount": 700,
      "total_rooms": 2,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 4,
      "smartlock_code": "8899#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Kini dijadikan sewaan bilik bulanan (Room Rental) - RM 700 / bulan. Rumah belakang.",
      "status": "active"
    },
    "guest": {
      "id": "gst-12",
      "name": "Arif Zulkifli",
      "phone": "0129881122",
      "email": "arifzulkifli@gmail.com",
      "notes": "Booking Planner: Arif zulkifli Sewa 1 Ogos 2026 (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-19",
    "property_id": "gong-badak",
    "guest_id": "gst-13",
    "check_in": "2026-08-01",
    "check_out": "2026-08-02",
    "total_nights": 1,
    "total_price": 350,
    "deposit_amount": 100,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Direct Booking 1 Ogos 2026 (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-13",
      "name": "Direct Booking 1 Ogos",
      "phone": "0120000000",
      "email": "directbooking1ogos@gmail.com",
      "notes": "Booking Planner: Direct Booking 1 Ogos 2026 (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-20",
    "property_id": "kemaman-2",
    "guest_id": "gst-14",
    "check_in": "2026-08-07",
    "check_out": "2026-08-08",
    "total_nights": 1,
    "total_price": 180,
    "deposit_amount": 100,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Stay 1 hari Athirah (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-2",
      "name": "Homestay Kenangan Kemaman 2",
      "address": "Chukai, Kemaman, Terengganu (Rumah Depan)",
      "rental_type": "daily",
      "base_price_per_night": 180,
      "price_direct": 180,
      "price_airbnb": 215,
      "price_bookingcom": 225,
      "cleaning_fee": 40,
      "deposit_amount": 100,
      "total_rooms": 3,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 8,
      "smartlock_code": "4422#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Rumah depan (3 bilik, 1 toilet, 1 bathroom). Lokasi & kemudahan sama dengan Kemaman 1.",
      "status": "active"
    },
    "guest": {
      "id": "gst-14",
      "name": "Athirah",
      "phone": "0198887766",
      "email": "athirah@gmail.com",
      "notes": "Booking Planner: Stay 1 hari Athirah (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-21",
    "property_id": "kemaman-2",
    "guest_id": "gst-15",
    "check_in": "2026-08-27",
    "check_out": "2026-08-29",
    "total_nights": 2,
    "total_price": 360,
    "deposit_amount": 100,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Boleh confirm tarikh check in dan check out Majlis Kahwin Nama: Kamariah (2 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-2",
      "name": "Homestay Kenangan Kemaman 2",
      "address": "Chukai, Kemaman, Terengganu (Rumah Depan)",
      "rental_type": "daily",
      "base_price_per_night": 180,
      "price_direct": 180,
      "price_airbnb": 215,
      "price_bookingcom": 225,
      "cleaning_fee": 40,
      "deposit_amount": 100,
      "total_rooms": 3,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 8,
      "smartlock_code": "4422#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Rumah depan (3 bilik, 1 toilet, 1 bathroom). Lokasi & kemudahan sama dengan Kemaman 1.",
      "status": "active"
    },
    "guest": {
      "id": "gst-15",
      "name": "Kamariah (Majlis Kahwin)",
      "phone": "0176655443",
      "email": "kamariahmajliskahwin@gmail.com",
      "notes": "Booking Planner: Boleh confirm tarikh check in dan check out Majlis Kahwin Nama: Kamariah (2 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-22",
    "property_id": "kemaman-2",
    "guest_id": "gst-16",
    "check_in": "2026-08-29",
    "check_out": "2026-09-01",
    "total_nights": 3,
    "total_price": 499,
    "deposit_amount": 100,
    "source": "airbnb",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Tarikh Disekat / Penyelenggaraan (3 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-2",
      "name": "Homestay Kenangan Kemaman 2",
      "address": "Chukai, Kemaman, Terengganu (Rumah Depan)",
      "rental_type": "daily",
      "base_price_per_night": 180,
      "price_direct": 180,
      "price_airbnb": 215,
      "price_bookingcom": 225,
      "cleaning_fee": 40,
      "deposit_amount": 100,
      "total_rooms": 3,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 8,
      "smartlock_code": "4422#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Rumah depan (3 bilik, 1 toilet, 1 bathroom). Lokasi & kemudahan sama dengan Kemaman 1.",
      "status": "active"
    },
    "guest": {
      "id": "gst-16",
      "name": "Pelanggan Airbnb Kemaman 2",
      "phone": "0167788990",
      "email": "pelangganairbnbkemaman2@gmail.com",
      "notes": "Booking Planner: Tarikh Disekat / Penyelenggaraan (3 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-23",
    "property_id": "gong-badak",
    "guest_id": "gst-17",
    "check_in": "2026-08-29",
    "check_out": "2026-09-05",
    "total_nights": 7,
    "total_price": 655,
    "deposit_amount": 100,
    "source": "airbnb",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Tarikh Disekat / Penyelenggaraan (7 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-17",
      "name": "Pelanggan Airbnb Gong Badak",
      "phone": "0167788991",
      "email": "pelangganairbnbgongbadak@gmail.com",
      "notes": "Booking Planner: Tarikh Disekat / Penyelenggaraan (7 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-24",
    "property_id": "kemaman-1",
    "guest_id": "gst-18",
    "check_in": "2026-09-01",
    "check_out": "2026-09-02",
    "total_nights": 1,
    "total_price": 700,
    "deposit_amount": 100,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Sewa (1 malam) Sewaan Bilik Bulanan Tetap RM700/bulan",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-1",
      "name": "Homestay Kenangan Kemaman 1",
      "address": "Chukai, Kemaman, Terengganu (Rumah Belakang)",
      "rental_type": "monthly",
      "monthly_rental_rate": 700,
      "base_price_per_night": 0,
      "price_direct": 0,
      "price_airbnb": 0,
      "price_bookingcom": 0,
      "cleaning_fee": 0,
      "deposit_amount": 700,
      "total_rooms": 2,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 4,
      "smartlock_code": "8899#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Kini dijadikan sewaan bilik bulanan (Room Rental) - RM 700 / bulan. Rumah belakang.",
      "status": "active"
    },
    "guest": {
      "id": "gst-18",
      "name": "En. Halim (Penyewa Sewa Bulanan)",
      "phone": "0134455667",
      "email": "enhalimpenyewasewabulanan@gmail.com",
      "notes": "Booking Planner: Sewa (1 malam) Sewaan Bilik Bulanan Tetap RM700/bulan",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-25",
    "property_id": "kemaman-2",
    "guest_id": "gst-19",
    "check_in": "2026-09-01",
    "check_out": "2026-09-02",
    "total_nights": 1,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Booking Planner: Standby (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-2",
      "name": "Homestay Kenangan Kemaman 2",
      "address": "Chukai, Kemaman, Terengganu (Rumah Depan)",
      "rental_type": "daily",
      "base_price_per_night": 180,
      "price_direct": 180,
      "price_airbnb": 215,
      "price_bookingcom": 225,
      "cleaning_fee": 40,
      "deposit_amount": 100,
      "total_rooms": 3,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 8,
      "smartlock_code": "4422#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Rumah depan (3 bilik, 1 toilet, 1 bathroom). Lokasi & kemudahan sama dengan Kemaman 1.",
      "status": "active"
    },
    "guest": {
      "id": "gst-19",
      "name": "Standby",
      "phone": "0190000010",
      "email": "standby@gmail.com",
      "notes": "Booking Planner: Standby (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-26",
    "property_id": "gong-badak",
    "guest_id": "gst-6",
    "check_in": "2026-09-06",
    "check_out": "2026-09-08",
    "total_nights": 2,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-6",
      "name": "Penyelenggaraan GB",
      "phone": "0190000000",
      "email": "penyelenggaraangb@gmail.com",
      "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-27",
    "property_id": "gong-badak",
    "guest_id": "gst-20",
    "check_in": "2026-09-10",
    "check_out": "2026-09-13",
    "total_nights": 3,
    "total_price": 1050,
    "deposit_amount": 100,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Wiraday (3 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-20",
      "name": "Wiraday",
      "phone": "0193344552",
      "email": "wiraday@gmail.com",
      "notes": "Booking Planner: Wiraday (3 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-28",
    "property_id": "kemaman-2",
    "guest_id": "gst-21",
    "check_in": "2026-09-18",
    "check_out": "2026-09-20",
    "total_nights": 2,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-2",
      "name": "Homestay Kenangan Kemaman 2",
      "address": "Chukai, Kemaman, Terengganu (Rumah Depan)",
      "rental_type": "daily",
      "base_price_per_night": 180,
      "price_direct": 180,
      "price_airbnb": 215,
      "price_bookingcom": 225,
      "cleaning_fee": 40,
      "deposit_amount": 100,
      "total_rooms": 3,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 8,
      "smartlock_code": "4422#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Rumah depan (3 bilik, 1 toilet, 1 bathroom). Lokasi & kemudahan sama dengan Kemaman 1.",
      "status": "active"
    },
    "guest": {
      "id": "gst-21",
      "name": "Penyelenggaraan K2",
      "phone": "0190000000",
      "email": "penyelenggaraank2@gmail.com",
      "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-29",
    "property_id": "kemaman-2",
    "guest_id": "gst-22",
    "check_in": "2026-09-24",
    "check_out": "2026-09-25",
    "total_nights": 1,
    "total_price": 250,
    "deposit_amount": 100,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Dh byr depo utk kawen (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-2",
      "name": "Homestay Kenangan Kemaman 2",
      "address": "Chukai, Kemaman, Terengganu (Rumah Depan)",
      "rental_type": "daily",
      "base_price_per_night": 180,
      "price_direct": 180,
      "price_airbnb": 215,
      "price_bookingcom": 225,
      "cleaning_fee": 40,
      "deposit_amount": 100,
      "total_rooms": 3,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 8,
      "smartlock_code": "4422#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Rumah depan (3 bilik, 1 toilet, 1 bathroom). Lokasi & kemudahan sama dengan Kemaman 1.",
      "status": "active"
    },
    "guest": {
      "id": "gst-22",
      "name": "Dh byr depo utk kawen",
      "phone": "0182233445",
      "email": "dhbyrdepoutkkawen@gmail.com",
      "notes": "Booking Planner: Dh byr depo utk kawen (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-30",
    "property_id": "kemaman-2",
    "guest_id": "gst-23",
    "check_in": "2026-09-25",
    "check_out": "2026-09-26",
    "total_nights": 1,
    "total_price": 250,
    "deposit_amount": 100,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Dh byr depo utk majlis kawen (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-2",
      "name": "Homestay Kenangan Kemaman 2",
      "address": "Chukai, Kemaman, Terengganu (Rumah Depan)",
      "rental_type": "daily",
      "base_price_per_night": 180,
      "price_direct": 180,
      "price_airbnb": 215,
      "price_bookingcom": 225,
      "cleaning_fee": 40,
      "deposit_amount": 100,
      "total_rooms": 3,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 8,
      "smartlock_code": "4422#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Rumah depan (3 bilik, 1 toilet, 1 bathroom). Lokasi & kemudahan sama dengan Kemaman 1.",
      "status": "active"
    },
    "guest": {
      "id": "gst-23",
      "name": "Dh byr depo utk majlis kawen",
      "phone": "0182233446",
      "email": "dhbyrdepoutkmajliskawen@gmail.com",
      "notes": "Booking Planner: Dh byr depo utk majlis kawen (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-31",
    "property_id": "gong-badak",
    "guest_id": "gst-6",
    "check_in": "2026-10-15",
    "check_out": "2026-10-17",
    "total_nights": 2,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-6",
      "name": "Penyelenggaraan GB",
      "phone": "0190000000",
      "email": "penyelenggaraangb@gmail.com",
      "notes": "Tarikh Disekat / Penyelenggaraan (2 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-32",
    "property_id": "gong-badak",
    "guest_id": "gst-24",
    "check_in": "2026-10-19",
    "check_out": "2026-10-20",
    "total_nights": 1,
    "total_price": 350,
    "deposit_amount": 100,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Konvo (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-24",
      "name": "Konvo",
      "phone": "0197766554",
      "email": "konvo@gmail.com",
      "notes": "Booking Planner: Konvo (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-33",
    "property_id": "gong-badak",
    "guest_id": "gst-25",
    "check_in": "2026-11-08",
    "check_out": "2026-11-09",
    "total_nights": 1,
    "total_price": 350,
    "deposit_amount": 100,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "fully_paid",
    "notes": "Booking Planner: Nama: Muhammad Fikri bin Ismail No. Telefon: 01139618066 (1 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-25",
      "name": "Muhammad Fikri bin Ismail",
      "phone": "01139618066",
      "email": "muhammadfikribinismail@gmail.com",
      "notes": "Booking Planner: Nama: Muhammad Fikri bin Ismail No. Telefon: 01139618066 (1 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-34",
    "property_id": "kemaman-2",
    "guest_id": "gst-26",
    "check_in": "2027-08-19",
    "check_out": "2027-09-21",
    "total_nights": 33,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Tarikh Disekat / Penyelenggaraan (33 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "kemaman-2",
      "name": "Homestay Kenangan Kemaman 2",
      "address": "Chukai, Kemaman, Terengganu (Rumah Depan)",
      "rental_type": "daily",
      "base_price_per_night": 180,
      "price_direct": 180,
      "price_airbnb": 215,
      "price_bookingcom": 225,
      "cleaning_fee": 40,
      "deposit_amount": 100,
      "total_rooms": 3,
      "total_bathrooms": 1,
      "total_toilets": 1,
      "max_guests": 8,
      "smartlock_code": "4422#",
      "wifi_ssid": "HomestayKenangan_Kemaman",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/KyBmg1iwgqLiSsha9",
      "notes": "Rumah depan (3 bilik, 1 toilet, 1 bathroom). Lokasi & kemudahan sama dengan Kemaman 1.",
      "status": "active"
    },
    "guest": {
      "id": "gst-26",
      "name": "Tarikh Disekat / Penyelenggaraan",
      "phone": "0190000000",
      "email": "tarikhdisekatpenyelenggaraan@gmail.com",
      "notes": "Tarikh Disekat / Penyelenggaraan (33 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  },
  {
    "id": "bk-verified-35",
    "property_id": "gong-badak",
    "guest_id": "gst-26",
    "check_in": "2027-08-25",
    "check_out": "2028-03-20",
    "total_nights": 208,
    "total_price": 0,
    "deposit_amount": 0,
    "source": "direct_whatsapp",
    "booking_status": "confirmed",
    "payment_status": "unpaid",
    "notes": "Tarikh Disekat / Penyelenggaraan (208 malam)",
    "created_at": "2026-09-24T11:46:42.234Z",
    "property": {
      "id": "gong-badak",
      "name": "Homestay Kenangan Gong Badak",
      "address": "Gong Badak, Kuala Terengganu, Terengganu",
      "rental_type": "daily",
      "base_price_per_night": 350,
      "price_direct": 350,
      "price_airbnb": 395,
      "price_bookingcom": 410,
      "cleaning_fee": 60,
      "deposit_amount": 150,
      "total_rooms": 4,
      "total_bathrooms": 4,
      "total_toilets": 4,
      "max_guests": 12,
      "smartlock_code": "1234#",
      "wifi_ssid": "HomestayKenangan_KT",
      "wifi_password": "kenangan2026!",
      "google_maps_url": "https://maps.app.goo.gl/SCBDByiRjyYQefny6",
      "notes": "Rumah banglo luas 4 bilik, 4 bathroom. Dekat pantai, airport & universiti.",
      "status": "active"
    },
    "guest": {
      "id": "gst-26",
      "name": "Tarikh Disekat / Penyelenggaraan",
      "phone": "0190000000",
      "email": "tarikhdisekatpenyelenggaraan@gmail.com",
      "notes": "Tarikh Disekat / Penyelenggaraan (33 malam)",
      "created_at": "2026-09-24T11:46:42.234Z"
    }
  }
];
