import { Property, Guest, Booking } from "./types";

export const mockProperties: Property[] = [
  {
    id: "prop-1",
    name: "Villa A - Poolside Garden",
    address: "No. 12, Jalan Damai 3, Kajang, Selangor",
    base_price_per_night: 280,
    cleaning_fee: 50,
    deposit_amount: 100,
    total_rooms: 3,
    max_guests: 8,
    smartlock_code: "8899#",
    wifi_ssid: "VillaDamai_5G",
    wifi_password: "damai2026!",
    status: "active",
  },
  {
    id: "prop-2",
    name: "Chalet B - Romantic Suite",
    address: "No. 14, Jalan Damai 3, Kajang, Selangor",
    base_price_per_night: 180,
    cleaning_fee: 30,
    deposit_amount: 50,
    total_rooms: 1,
    max_guests: 3,
    smartlock_code: "4422#",
    wifi_ssid: "ChaletSuite_WiFi",
    wifi_password: "suiteguest123",
    status: "active",
  },
  {
    id: "prop-3",
    name: "Homestay C - Family Classic",
    address: "No. 16, Jalan Damai 3, Kajang, Selangor",
    base_price_per_night: 350,
    cleaning_fee: 60,
    deposit_amount: 150,
    total_rooms: 4,
    max_guests: 12,
    smartlock_code: "1234#",
    wifi_ssid: "FamilyClassic_Guest",
    wifi_password: "keluargabahagia",
    status: "active",
  },
];

export const mockGuests: Guest[] = [
  {
    id: "gst-1",
    name: "Ahmad Farhan",
    phone: "0134567890",
    email: "farhan@example.com",
    notes: "Family gathering (8 pax)",
  },
  {
    id: "gst-2",
    name: "Nurul Huda",
    phone: "0198765432",
    email: "huda@example.com",
    notes: "Repeat guest - minta extra pillow",
  },
  {
    id: "gst-3",
    name: "Tan Wei Lun",
    phone: "0123344556",
    email: "weilun@example.com",
    notes: "Booking via WhatsApp Direct",
  },
];

export const mockBookings: Booking[] = [
  {
    id: "bk-101",
    property_id: "prop-1",
    guest_id: "gst-1",
    check_in: "2026-09-18",
    check_out: "2026-09-20",
    total_nights: 2,
    total_price: 610, // (280*2) + 50 cleaning
    deposit_amount: 100,
    source: "direct_whatsapp",
    booking_status: "confirmed",
    payment_status: "deposit_paid",
    notes: "Dah bayar deposit RM100. Baki RM510 bayar masa check-in.",
    property: mockProperties[0],
    guest: mockGuests[0],
  },
  {
    id: "bk-102",
    property_id: "prop-2",
    guest_id: "gst-2",
    check_in: "2026-09-17",
    check_out: "2026-09-18",
    total_nights: 1,
    total_price: 210,
    deposit_amount: 50,
    source: "airbnb",
    booking_status: "checked_in",
    payment_status: "fully_paid",
    notes: "Check-in hari ini.",
    property: mockProperties[1],
    guest: mockGuests[1],
  },
  {
    id: "bk-103",
    property_id: "prop-3",
    guest_id: "gst-3",
    check_in: "2026-09-22",
    check_out: "2026-09-25",
    total_nights: 3,
    total_price: 1110,
    deposit_amount: 150,
    source: "direct_whatsapp",
    booking_status: "pending",
    payment_status: "unpaid",
    notes: "Menunggu bukti bayaran deposit.",
    property: mockProperties[2],
    guest: mockGuests[2],
  },
];
